IMAGE_NAME=wi-azservicebus
CATEGORY=AzureServiceBus
DOCS_ZIP=Azure-Service-Bus.zip
PRODUCT_ID=flogo-azservicebus
VERSION=1.1.0
JIRAID=WIAZSB
TC_BUILDNO=15
TC_BUILD_ID=Atmosphere_WiConnectors_FlogoConnectors_AzureServiceBus
VBUILDNO=9
LEGACY_BUILD=false
PRODUCT_DESCRIPTION="Flogo Azure Service Bus Connector"
DOCKER_REPO=https://reldocker.tibco.com/repositories/wasp/wi-azservicebus/tags
FE_REPO=http://reldist.na.tibco.com/package/flogo-azservicebus
EMAIL_FROM=vbansal@tibco.com
EMAIL_TO="vbansal@tibco.com, okulkarn@tibco.com, jdutta@tibco.com, bvenkata@tibco.com, ravgupta@tibco.com, ukuppa@tibco.com, johndrv@tibco.com, jdg@tibco.com, nkamble@tibco.com, pdogra@tibco.com"
EMAIL_ADMIN=vbansal@tibco.com
