IMAGE_NAME=wi-azservicebus
CATEGORY=AzureServiceBus
DOCS_ZIP=Azure-Service-Bus.zip
PRODUCT_ID=flogo-azservicebus
VERSION=1.2.0
JIRAID=WIAZSB
TC_BUILDNO=16
TC_BUILD_ID=Atmosphere_WiConnectors_FlogoConnectors_AzureServiceBus
VBUILDNO=01
LEGACY_BUILD=false
PRODUCT_DESCRIPTION="Flogo Azure Service Bus Connector"
DOCKER_REPO=https://reldocker.tibco.com/tci/wi-azservicebus
FE_REPO=http://reldist.na.tibco.com/package/flogo-azservicebus
EMAIL_FROM=vbansal@tibco.com
EMAIL_TO="psatalka@tibco.com, nkamble@tibco.com, johndrv@tibco.com, jdutta@tibco.com, swagupta@tibco.com, pukumar@tibco.com,vsawariy@tibco.com"
EMAIL_ADMIN=svc-connectorsuser@tibco.com
